# Generated by Django 2.2.2 on 2019-06-24 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.apps.examples.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', upload_to=project.apps.examples.models.path_and_rename)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples_object_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
                'ordering': ['-created_at'],
            },
        ),
    ]
